import React, {useState} from 'react';
import {Animated, Easing} from 'react-native';
import BootSplash from 'react-native-bootsplash';
import {useWardrobeContext} from '../state/WardrobeContext';

// Generated by `npm run generate:splash`, together with the native launch screens.
const manifest = require('../assets/bootsplash/manifest.json');
const logoSource = require('../assets/bootsplash/logo.png');

/**
 * Takes over from the native launch screen (white, with the hanger in the
 * centre) once the saved wardrobe has loaded, then fades away: the hanger
 * fades out while growing a little, and the white fades after it to reveal
 * the app.
 */
export function SplashScreen() {
  const {wardrobe} = useWardrobeContext();
  const [done, setDone] = useState(false);
  const [logoOpacity] = useState(() => new Animated.Value(1));
  const [opacity] = useState(() => new Animated.Value(1));

  const {container, logo} = BootSplash.useHideAnimation({
    manifest,
    logo: logoSource,
    ready: wardrobe.loaded,
    animate: () => {
      Animated.parallel([
        Animated.timing(logoOpacity, {
          toValue: 0,
          duration: 300,
          easing: Easing.in(Easing.quad),
          useNativeDriver: true,
        }),
        Animated.timing(opacity, {
          toValue: 0,
          duration: 350,
          delay: 150,
          easing: Easing.out(Easing.quad),
          useNativeDriver: true,
        }),
      ]).start(() => setDone(true));
    },
  });

  if (done) {
    return null;
  }
  const scale = logoOpacity.interpolate({
    inputRange: [0, 1],
    outputRange: [1.15, 1],
  });
  return (
    <Animated.View {...container} style={[container.style, {opacity}]}>
      <Animated.Image
        {...logo}
        style={[logo.style, {opacity: logoOpacity, transform: [{scale}]}]}
      />
    </Animated.View>
  );
}
