/**
 * Bundles webview/scene.js (three.js + the blank garment models) into one
 * self-contained HTML string for the app's WebView:
 *   src/webview/sceneHtml.ts
 *
 * Run `npm run generate:models` first if the models changed, then
 * `npm run build:webview`. The output is committed so the app needs no
 * bundling step at runtime.
 */
const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');

const root = path.join(__dirname, '..');
const outFile = path.join(root, 'src', 'webview', 'sceneHtml.ts');

const {outputFiles} = esbuild.buildSync({
  entryPoints: [path.join(root, 'webview', 'scene.js')],
  bundle: true,
  minify: true,
  format: 'iife',
  target: 'es2020',
  write: false,
  loader: {'.glb': 'base64'},
  legalComments: 'none',
});

// A literal "</script" would end the inline script early.
const js = outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<style>
  html, body { margin: 0; height: 100%; overflow: hidden; background: #ece7df; }
  canvas { display: block; touch-action: none; -webkit-user-select: none; user-select: none; }
</style>
</head>
<body>
<script>${js}</script>
</body>
</html>`;

fs.mkdirSync(path.dirname(outFile), {recursive: true});
fs.writeFileSync(
  outFile,
  `// Generated by scripts/build-webview.js. Do not edit.\n/* eslint-disable */\nexport const SCENE_HTML = ${JSON.stringify(html)};\n`,
);
console.log(`sceneHtml.ts: ${(html.length / 1024).toFixed(0)} KB`);
